### PR TITLE
Wip/development seeder fix

### PR DESCRIPTION
**Pull request by jnelson180**
## Description
Fixes `DevelopmentSeeder.php` and updates node modules so that the dev onboarding process in `contributing.md` works as intended.

## Motivation and Context
Previously (when I cloned into the repo today), following the instructions from `contributing.md` would cause breakages at seeding and at `npm run dev`.

## How Has This Been Tested?
I am now able to build the project and set it up / run local server.

## Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by WaveHack** [comment]
I get the PHP changes, since I did some refactoring in the factories earlier (and forgot to update the seeder, whoops!).

I'm not sure however about the npm package. I never really had much troubles with this, let alone having to import a React babel package of all things.

Could you remove it for me (basically reset the state of your codebase back to develop when you encountered this issue) and paste the error you got with `npm run dev` in here?

**Comment by jnelson180** [comment]
Very odd- actually, I'm not sure what happened there. I did a good bit of tinkering with it to get it to build, and that was probably an artifact left from something I tried out. 

Originally, I couldn't get `npm run dev` to work (an error was being thrown about babel presets not being set up correctly). I ended up trying `babel-preset-react` because I've used it before to add presets into (well, a React project, but anyway) and totally forgot to replace it with something else once I confirmed presets fixed the issue I was having.

Well, now I've reinstalled node and npm, cloned the repo freshly, and ran through the install process again just with the seeder changes and everything is working fine without any presets at all. I think that my node and npm versions must have been out of whack or something. 

Reverted back to develop version of package.json. Sorry about that!!

**Comment by WaveHack** [comment]
No worries! Thanks for testing it for me. 😄

**Comment by jnelson180** [comment]
Oh, good call. Updated in [264eb4f1](https://github.com/WaveHack/OpenDominion/pull/479/commits/264eb4f182c4bac9528d6ef2bafa0e4fef5a5ff0).

**Comment by WaveHack** [comment]
And merged.

Thanks for the find (and the fix)! Much appreciated

**Pull request merged**
