### PR TITLE
Update invasion calculator

### PR DESCRIPTION
**Pull request by internetfett**
Features
- Adds new API route group with invasion calculator endpoint.
- Connected to existing frontend code with minimal changes.
- Updates unit OP/DP onload and when selecting a target.
- Takes into account building/land-based perks as well as target range/race perks.

Bugfixes
- Errors with default value of opposingForceRaceName
- Errors with RezoningCalculator constructor  
- Errors with multi-argument functions in DebugController
- Update validation for InvadeActionServiceRequest
- reverse order of offense_staggered_land_range (Dark Elf/Gnome)
- correct indentation on need_boats (Dark Elf)
- correct typo in perk (Dark Elf)

Todo
- Should be refactored a bit in the future to do most/all of the calculations on the backend.

### CODE REVIEW

**Comment by WaveHack** [comment]
Thanks! I'll check it out tomorrow or Wednesday

**Comment by stromblom** [comment]
The other changes look good to me. So if you check the api bit @WaveHack I'm good.

**Comment by WaveHack** [comment]
Thanks @stromblom!

**Comment by WaveHack** [comment]
Looks good. I'll merge and test it out

**Pull request merged**
