### PR TITLE
Add starvation due to lack of food

### LINKED ISSUE #42: Add starvation due to lack of food
Need help on the formula for it

### PR DESCRIPTION
**Pull request by guilhermeportela**
Closes #42 and #103.

I'm sorry, but unfortunately I wasn't able to develop the test methods.

### CODE REVIEW

**Comment by WaveHack** [comment]
Thanks for the PR! I'll check it in a bit.

No worries about the unit tests. I've been very lazy on them myself at the moment. One day...

**Comment by guilhermeportela** [comment]
One problem though, @WaveHack: if the population reaches 0, it throws a division by zero exception once the percentages of the population are calculated. Should I fix it, or it should'nt happen (population reach zero)?

**Comment by WaveHack** [comment]
I think if the population of your dominion ever reaches 0, it's game over, and the player is allowed to re-register a new dominion in the same round.

I need to do more research on this on how I want to tackle it for OD. So thanks for bringing it up, but I don't think it's necessary to fix it right now.

**Comment by guilhermeportela** [comment]
The algorithm does the following:
- It calculates total casualties (negative food * 4)
- It calculates peasants casualties (total casualties / 2 or the amount of peasants, if it's lower than a half of the total casualties)
- It evenly distributes casualties between the military units (or it uses its amount of soldiers, if it's lower)
- If there's still any remaining casualties to be taken into account, it's distributed to the peasants (or all peasants if the amount is lower than the remaining casualties + already calculated casualties of peasants)
- It sets food resources to 0

**Comment by WaveHack** [comment]
Sounds good. Still in the process of checking it.

And I saw you made a CasualtiesCalculator. 😄 I think it's pretty cool. Haven't thought of that myself to do it this way.

Note to self: I think either the method names or method location need some refactoring later when there are casualties from other sources, namely:

- Casualties from invasions, both on the sending end (the units you send) and receiving end (any military units at home during the invasions).
- Draftee/Wizard casualties from assassination spy ops.
- Peasant casualties if you receive a Fireball magic spell.

I've not decided yet if I want to have one central place for all of those (i.e. CasualtiesCalculator), or move the methods to their appropriate classes (ProductionCalculator for starvation, CombatCalculator for invasions, EspionageCalculator for assa ops and SpellCalculator for Fireball).

**Comment by Hodgy** [comment]
> I've not decided yet if I want to have one central place for all of those (i.e. CasualtiesCalculator), or move the methods to their appropriate classes (ProductionCalculator for starvation, CombatCalculator for invasions, EspionageCalculator for assa ops and SpellCalculator for Fireball)

I would split them into separate classes under a casualties namespace

**Comment by WaveHack** [comment]
Minor nitpick, because it loops over all available units, subtracts casualties for each unit and then checks for remaining casualties, some values give off results, usually resulting in more casualties than desired.

In my case, this happens when negative food is -1 (with just the starting units):

```PHP
array:1 [
  0 => array:5 [
    "peasants" => 2
    "military_unit2" => 1
    "military_spies" => 1
    "military_wizards" => 1
    "military_draftees" => 1
  ]
]
```

Or with -3 food:

```PHP
array:1 [
  0 => array:5 [
    "peasants" => 6
    "military_unit2" => 2
    "military_spies" => 2
    "military_wizards" => 2
    "military_draftees" => 2
  ]
]
```

Should in practice almost never happen, but I fixed it regardless.

**Comment by WaveHack** [comment]
Thanks for the PR! Really awesome job on this one. 😄

**Comment by guilhermeportela** [comment]
You're welcome, @WaveHack. I'm glad I was able to help :smile:

**Pull request merged**
